# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'RxSwift Study' do

pod 'RxSwift'
pod 'RxCocoa'
pod 'RxGesture'
pod 'RxDataSources'
pod 'RxKeyboard'


end
